stages:
  - build-aws-deployer
  - test-aws-deployer
  - build-aws-deployer-docker
  - test-aws-deployer-docker

.job_template: &test-aws-deployer-template
  stage: test-aws-deployer
  script:
    - aws --version
  tags:
    - vanilla

.job_template: &test-aws-deployer-docker-template
  stage: test-aws-deployer-docker
  script:
    - aws --version
    - docker build aws-deployer-docker/
  tags:
    - dind
  dependencies:
    - build-aws-deployer-docker

variables:
  DOCKER_DRIVER: overlay2  

build-aws-deployer:
  stage: build-aws-deployer
  script:
    - VERSION=$(cat aws-deployer/VERSION)
    - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
    - >
      docker build 
      -t matsskoglund/aws-deployer:$VERSION
      -t matsskoglund/aws-deployer:latest 
      aws-deployer/.
    - docker push matsskoglund/aws-deployer:latest
    - docker push matsskoglund/aws-deployer:$VERSION    
  tags: 
    - dind

test-aws-deployer-latest:
  image:  matsskoglund/aws-deployer:latest
  <<: *test-aws-deployer-template

test-aws-deployer-empty:
  stage: test
  image:  matsskoglund/aws-deployer
  <<: *test-aws-deployer-template

test-aws-deployer-semver:
  stage: test
  image:  matsskoglund/aws-deployer
  <<: *test-aws-deployer-template

build-aws-deployer-docker:
  stage: build-aws-deployer-docker
  before_script:
    - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
  script:
    - VERSION=$(cat aws-deployer/VERSION)
    - >
      docker build 
      -t matsskoglund/aws-deployer:$VERSION-docker 
      aws-deployer-docker/.    
    - docker push matsskoglund/aws-deployer:$VERSION-docker
  tags:
    - dind
  dependencies:
    - test-aws-deployer-latest

test-aws-deployer-docker-docker:
  image:  matsskoglund/aws-deployer:docker
  <<: *test-aws-deployer-docker-template
  
test-aws-deployer-docker-semver:
  image:  matsskoglund/aws-deployer:$VERSION-docker
  <<: *test-aws-deployer-docker-template  
